export const USERNAME = process.env.KOBITON_USERNAME || 'kobiton_username'
export const API_KEY = process.env.KOBITON_API_KEY || 'kobiton_api_key'
export const DEVICE_NAME = process.env.KOBITON_DEVICE_NAME || 'kobiton_device_name'
export const PLATFORM_NAME = process.env.KOBITON_PLATFORM_NAME || 'kobiton_platform_name'
export const APP = process.env.KOBITON_APP || 'kobiton_app'
export const ROOT_DIR = process.env.KOBITON_ROOT_DIR || 'app_file_root_directory'
export const FILE_NAME = process.env.KOBITON_FILE_NAME || 'app_file_name'
